# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxRUZsUYmNWn2HMxkDK3IiVfsnnfZh8t
"""

import math
import cv2
from ultralytics import YOLO

# Cargar el modelo (asegúrate de tener el archivo best.pt en la misma carpeta)
model = YOLO('best.pt')

# Inicializar la cámara
capture = cv2.VideoCapture(0)
capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

while True:
    success, img = capture.read()
    if not success:
        print("No se puede acceder a la cámara.")
        break

    # Detección con el modelo YOLO
    results = model(img, stream=True, conf=0.2)

    for r in results:
        boxes = r.boxes
        for box in boxes:
            cls = int(box.cls[0])
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)

            confidence = math.ceil((box.conf[0] * 100)) / 100
            label = model.names[cls]

            cv2.putText(img, f'{label} {confidence}',
                        (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX,
                        0.7, (0, 255, 0), 2)

    cv2.imshow('Detection', img)

    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

capture.release()
cv2.destroyAllWindows()