# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWKkMdeXE0zf-YzP_sh9lSBKfYHluOQ_
"""

import math
import cv2
from ultralytics import YOLO

# Carga del modelo (asegúrate de que best.pt esté en la misma carpeta que este archivo)
model = YOLO('best.pt')

# Configuración de la cámara
capture = cv2.VideoCapture(0)
capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

while True:
    success, img = capture.read()
    if not success:
        print("No se puede acceder a la cámara.")
        break

    # Inferencia con YOLO
    results = model(img, stream=True, conf=0.3)

    for r in results:
        boxes = r.boxes

        for box in boxes:
            cls = int(box.cls[0])

            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)

            confidence = math.ceil((box.conf[0] * 100)) / 100

            label = model.names[cls]

            cv2.putText(img, f'{label} {confidence}',
                        (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX,
                        0.7, (0, 255, 0), 2)

    cv2.imshow('Detection', img)

    # Presiona "q" para salir
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

capture.release()
cv2.destroyAllWindows()